import { createAction } from "redux-actions";

// export const actionNames = {
//   FETCH_RECIPES: "RECIPES/FETCH_RECIPES",
// };

export default {
  "RECIPES/FETCH_RECIPES": createAction("RECIPES/FETCH_RECIPES"),
  "RECIPES/FETCH_SUCCESSFULLY": createAction("RECIPES/FETCH_SUCCESSFULLY"),

  "RECIPES/DATA_ERROR": createAction("RECIPES/DATA_ERROR"),

  "RECIPES/SAVE_NEW_RECIPE": createAction("RECIPES/SAVE_NEW_RECIPE"),
  "RECIPES/ADD_NEW_RECIPE_SUCCESSFULLY": createAction(
    "RECIPES/ADD_NEW_RECIPE_SUCCESSFULLY"
  ),

  "RECIPES/DELETE_ALL_RECIPES": createAction("RECIPES/DELETE_ALL_RECIPES"),
  "RECIPES/DELETE_ALL_RECIPES_SUCCESSFULLY": createAction(
    "RECIPES/DELETE_ALL_RECIPES_SUCCESSFULLY"
  ),

  "RECIPES/DELETE_SINGLE_RECIPE": createAction("RECIPES/DELETE_SINGLE_RECIPE"),
  "RECIPES/DELETE_SINGLE_RECIPE_SUCCESSFULLY": createAction(
    "RECIPES/DELETE_SINGLE_RECIPE_SUCCESSFULLY"
  ),

  "RECIPES/EDIT_RECIPE": createAction("RECIPES/EDIT_RECIPE"),
  "RECIPES/EDIT_RECIPE_SUCCESSFULLY": createAction(
    "RECIPES/EDIT_RECIPE_SUCCESSFULLY"
  ),
};
